wstat <- read.csv("6/wstat.csv", header=TRUE)
# スケーリング
swstat <- scale(wstat)
# 距離行列の作成(ユークリッド距離)
dwstat <- dist(swstat, method="euclidean")
# 階層的クラスタリング(ウォード法)
clusters_ward <- hclust(dwstat, method="ward.D2")
png("6/cutree_ward.png")
plot(clusters_ward, xlab="City", hang=-1)
dev.off()
# 階層的クラスタリング(群平均法)
clusters_ave <- hclust(dwstat, method="average")
png("6/cutree_average.png")
plot(clusters_ave, xlab="City", hang=-1)
dev.off()

# クラスタ数を８として表示(ウォード法)
cutree(clusters_ward, k=8)
# クラスタ数を８として表示(群平均法)
cutree(clusters_ave, k=8)